#!/usr/bin/env node

var fs = require('fs'),
	jade = require('jade'),
	marked = require('marked');


render([
	//Templates for rendering
	'index', 'contacts', 'schedule', 'about'
]);


function render(templates) {
	templates.map(function(name) {
		var templatePath = './templates/pages/' + name + '.jade',
			template = fs.readFileSync(templatePath),
			contentPath = './content/pages/' + name + '.md',
			content = null;
		if (fs.existsSync(contentPath)) {
			console.log(
				'Using content `%s` for template `%s', contentPath, templatePath
			);
			content = marked(fs.readFileSync(contentPath).toString());
		}
		var html = jade.compile(template, {
			filename: templatePath,
			pretty: true
		})({
			content: content
		});
		fs.writeFileSync(name + '.html', html);
	});
}
