#!/usr/bin/env node

var fs = require('fs'),
	jade = require('jade');


render([
	//Templates for rendering
	'index', 'contacts', 'schedule', 'about'
]);


function render(templates) {
	templates.map(function(name) {
		var path = 'templates/' + name + '.jade',
			template = fs.readFileSync(path),
			html = jade.compile(template, {filename: path})();
		fs.writeFileSync(name + '.html', html);
	});
}
